// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDf1DYm3yA-6lAOmVQ3cgRcmnuRWzQgJ0E',
    appId: '1:355876109241:web:865afaf0e4b8ee3dcc1468',
    messagingSenderId: '355876109241',
    projectId: 'tna-toptan-11fe3',
    authDomain: 'tna-toptan-11fe3.firebaseapp.com',
    storageBucket: 'tna-toptan-11fe3.appspot.com',
    measurementId: 'G-ZW55LY5Q6N',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAJScin-kvAH9AQC9Z1Drx8QrGeVDP0fQg',
    appId: '1:355876109241:android:02e3e07387e214dfcc1468',
    messagingSenderId: '355876109241',
    projectId: 'tna-toptan-11fe3',
    storageBucket: 'tna-toptan-11fe3.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCRsLV-7VB-Z6BchEHoaaefOtG8XncpqYM',
    appId: '1:355876109241:ios:a09fe8d4730373d5cc1468',
    messagingSenderId: '355876109241',
    projectId: 'tna-toptan-11fe3',
    storageBucket: 'tna-toptan-11fe3.appspot.com',
    iosBundleId: 'com.example.tnaToptan',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCRsLV-7VB-Z6BchEHoaaefOtG8XncpqYM',
    appId: '1:355876109241:ios:834ebf9a3b6baa7ecc1468',
    messagingSenderId: '355876109241',
    projectId: 'tna-toptan-11fe3',
    storageBucket: 'tna-toptan-11fe3.appspot.com',
    iosBundleId: 'com.example.tnaToptan.RunnerTests',
  );
}
